"""
Category Examples for RAG-Based Classification

This module contains rich examples for each question category to enable
semantic similarity-based classification instead of hardcoded regex patterns.

Each category includes:
- Description: What this category covers
- In-scope examples: Questions that belong to this category
- Out-of-scope examples: Similar questions that DON'T belong here
- Boundary cases: Ambiguous examples that need clarification
- Keywords: Important terms (for hybrid search)
"""

from typing import Dict, List, Any

# ============================================================================
# LIBRARY SERVICES CATEGORIES (In-Scope)
# ============================================================================

LIBRARY_EQUIPMENT_CHECKOUT = {
    "category": "library_equipment_checkout",
    "description": "Questions about borrowing library equipment like laptops, computers, chargers, cameras, calculators, or software licenses (Adobe, etc.). The library provides these for checkout.",
    "agent": "policy_or_service",
    "in_scope_examples": [
        "Can I borrow a laptop from the library?",
        "Do you have computers available for checkout?",
        "Can I check out a Chromebook?",
        "Does the library have laptop chargers?",
        "Can I rent a camera from the library?",
        "Do you have calculators to borrow?",
        "How do I get Adobe?",
        "How can I checkout Adobe?",
        "Adobe suite",
        "Adobe license",
        "Adobe for undergraduate students",
        "Adobe for faculty",
        "Adobe for staff",
        "Adobe for graduate students",
        "Acrobat",
        "Acrobat for undergraduate students",
        "Acrobat for faculty",
        "Acrobat for staff",
        "Acrobat for graduate students",
        "Can I get Adobe software from the library?",
        "Does the library loan out headphones?",
        "Can I checkout an iPad?",
        "Are there tripods available?",
        "Can I borrow equipment for my project?",
        "Do you have MacBooks for checkout?",
        "Can I get a laptop adapter?",
        "Does the library have desktop computers I can use?",
        "Can I checkout software licenses?",
        "Do you loan out electronic equipment?",
        "Can I borrow a GoPro?",
        "Do you have video cameras?",
        "Can I check out a laptop?",
        "Do you have laptops for checkout?",
        "Can I borrow a computer?",
        "Laptop checkout",
        "Can I get a laptop?",
        "Do you have a copy of Frankenstein?",
        "Do you have a copy of Harry Potter?",
        "Got Harry Potter?",
        "Got a copy of [book name]?",
        "Do you have [book title]?",
        "Is [book name] available?",
        "Can I find [book] here?",
        "Do you carry [book title]?",
        "Looking for a book called [title]",
        "Are there audio recorders?",
        "Can I borrow presentation equipment?",
        "Do you have webcams?",
        "Can I check out a tablet?",
        "Are there drawing tablets?",
        "Can I borrow VR equipment?",
        "Can I get Adobe Creative Cloud?",
        "Do you have SPSS?",
        "Can I borrow statistical software?",
        "Is Photoshop available?",
        "Can I get video editing software?",
        "Do you have Microsoft Office?",
        "Can I check out design software?",
        "I need a computer",
        "I need a laptop",
        "Can I get a computer?",
        "Do you have a laptop I can use?",
        "I don't have a laptop, can you help?",
        "I need to borrow a computer",
        "Can I borrow a laptop at Hamilton?",
        "Does Rentschler Library have laptops?",
        "Equipment checkout at Middletown",
        "Can I borrow equipment at Gardner-Harvey Library?",
        "Does the Hamilton campus library have cameras?",
        "Middletown library equipment",
        "Regional campus laptop checkout",
        "Can I get a charger at Rentschler?",
        "Does Middletown have calculators?",
    ],
    "out_of_scope_examples": [],
    "boundary_cases": [
        {
            "question": "I have a question about computers",
            "clarification_needed": "Are you asking about: (1) Borrowing/checking out a computer from the library, or (2) Getting help with a computer problem/repair?",
            "possible_categories": ["library_equipment_checkout", "out_of_scope_tech_support"]
        },
        {
            "question": "Who can help me with computer stuff?",
            "clarification_needed": "Are you asking about: (1) Borrowing library computers/equipment, or (2) Technical support for computer problems?",
            "possible_categories": ["library_equipment_checkout", "out_of_scope_tech_support"]
        },
    ],
    "keywords": ["borrow", "checkout", "check out", "rent", "loan", "laptop", "computer", "chromebook", "equipment", "device", "camera", "calculator", "adobe", "software", "charger", "ipad", "macbook"],
}

LIBRARY_HOURS_ROOMS = {
    "category": "library_hours_rooms",
    "description": "Questions about library building hours, schedules, or room reservations/bookings.",
    "agent": "booking_or_hours",
    "in_scope_examples": [
        "What time does King Library close?",
        "What time does the library close?",
        "When does King Library open?",
        "Library hours",
        "What are the library hours?",
        "What are the library hours for The King Library?",
        "Answer for MLK hours for The King Library",
        "MLK hours",
        "Martin Luther King Jr. Library hours",
        "Is the library open now?",
        "When does the library close today?",
        "Are you open on weekends?",
        "What time does King close on Friday?",
        "Library hours for tomorrow",
        "When does the library open on Sunday?",
        "Is King Library open 24 hours?",
        "Late night hours",
        "Are you open during break?",
        "Library hours during finals week",
        "Are study rooms available?",
        "Book a study room",
        "How do I reserve a study room?",
        "Can I book a room?",
        "Study room reservation",
        "Group study space",
        "Where can I study?",
        "What time does Wertz Library close?",
        "Art and Architecture Library hours",
        "Art and Architecture hours",
        "Art & Architecture hours",
        "Art and Architecture test with and without Wertz",
        "Wertz Art and Architecture Library",
        "Hours for Art and Architecture",
        "When is Special Collections open?",
        "Special Collections hours",
        "Special Collections test with and without full name",
        "What are Special Collections hours?",
        "When is Special Collections available?",
        "Archives hours",
        "Regional library hours",
        "Are you open during spring break?",
        "What time do you close on Friday?",
        "Weekend hours",
        "Holiday hours",
        "Are group study rooms available?",
        "Can I book a room for 3 hours?",
        "Study room availability",
        "Where is the MakerSpace?",
        "Makerspace hours",
        "What time does Makerspace close?",
        "When is Makerspace open?",
        "Makerspace schedule",
        "Faculty reading room location",
        "Graduate reading room",
        "Where can I study quietly?",
        "Silent study areas",
        "Computer lab locations",
        "How many computers are available?",
        "Where is the Howe Writing Center?",
        "Where is the TEC Lab?",
        "TEC Lab Makerspace hours",
        "Middletown Makerspace",
        "When is the TEC Lab open?",
        "Gardner-Harvey Makerspace location",
        "TEC Lab at Middletown",
        "Makerspace at regional campus",
        "3D printing",
        "3D print something",
        "How to 3D print?",
        "3D printer access",
        "Can I 3D print at the library?",
        "Where can I 3D print?",
        "3D printing services",
        "Makerspace 3D printing",
        "Where is the library?",
        "Where is the library located?",
        "How do I get to the library?",
        "Where tf is the library?",
        "Library location",
        "Directions to library",
        "What time does Rentschler Library close?",
        "When does Gardner-Harvey Library open?",
        "Hamilton library hours",
        "Middletown library hours",
        "Hours for Rentschler",
        "When is Gardner-Harvey open?",
        "Regional campus library hours",
        "Hamilton campus library schedule",
        "Middletown campus hours",
        "Is Rentschler open on weekends?",
        "Gardner-Harvey weekend hours",
        "Book a study room at Hamilton",
        "Reserve a room at Rentschler",
        "Study room at Middletown",
        "Gardner-Harvey study rooms",
        "Can I book a room at the regional campus?",
        "Hamilton campus study space",
        "Middletown study room reservation",
        "Where is Rentschler Library?",
        "How do I get to Gardner-Harvey?",
        "Hamilton library location",
        "Middletown library address",
        "What is the address of the library?",
        "What is the address of the King Library?",
        "What is the library address?",
        "Library address",
        "King Library address",
        "King address",
        "Address of the library",
        "Address of King Library",
        "Where is the library?",
        "Where is the library located?",
        "Where is King Library?",
        "Library location",
        "What is the library phone number?",
        "Library phone number",
        "King Library phone number",
        "How do I contact the library?",
        "Library contact information",
        "Phone number for Rentschler Library",
        "Hamilton library phone number",
        "Middletown library phone number",
        "Gardner-Harvey phone number",
        "What is the address of all library locations?",
        "Give me addresses for Oxford, Hamilton, and Middletown libraries",
        "Phone numbers for all three campuses",
        "Contact information for main and regional campuses",
        "Addresses for King, Rentschler, and Gardner-Harvey",
        "How do I reach each library?",
        "Contact info for all campuses",
        "Phone numbers for Oxford, Hamilton, and Middletown",
        "Addresses and phone numbers for all libraries",
        "How do I contact King, Rentschler, and Gardner-Harvey?",
        "Give me contact information for all three library locations",
        "What are the addresses of the main and regional libraries?",
    ],
    "out_of_scope_examples": [
        "When is class registration?",
        "What time does the dining hall close?",
        "When is the football game?",
        "Can I drink at Gardner-Harvey?",
        "Research assistance at Middletown",
        "Gardner-Harvey research help",
        "Printing at Hamilton",
        "Printing at Rentschler",
        "Middletown library printing",
        "Gardner-Harvey printing",
        "Hamilton campus printing",
        "Middletown campus printing",
        "2D printing",
        "Paper printing",
        "MUprint",
        "Web Print",
        "Printing costs",
    ],
    "boundary_cases": [],
    "keywords": ["hours", "open", "close", "schedule", "book", "reserve", "room", "study room", "library hours"],
}

SUBJECT_LIBRARIAN_GUIDES = {
    "category": "subject_librarian_guides",
    "description": "Finding subject librarians by discipline, or finding LibGuides/research guides for a specific subject or major.",
    "agent": "subject_librarian",
    "in_scope_examples": [
        "Who is the biology librarian?",
        "Who is the engineering librarian?",
        "Who is the psychology librarian?",
        "Who is the English librarian?",
        "Who is the nursing librarian?",
        "Who is the business librarian?",
        "Who is the chemistry librarian?",
        "Who is the history librarian?",
        "Subject librarian for computer science",
        "Librarian for my major",
        "Who can help with physics research?",
        "Find a librarian for sociology",
        "Who is the liaison librarian for art?",
        "LibGuide for biology",
        "Research guide for nursing",
        "Do you have a guide for psychology?",
        "LibGuide for ENG 111",
        "Is there a class guide for my class - BUS 217, ENG 111, BIO 201",
        "Class guide for BUS 217",
        "Guide for ENG 111",
        "BIO 201 LibGuide",
        "Research guide for BUS 217",
        "Course guide for ENG 111",
        "Research guide for my class",
        "Where can I find the business LibGuide?",
        "Who is the art librarian?",
        "Music librarian contact",
        "Political science librarian",
        "Sociology librarian",
        "Anthropology librarian",
        "Philosophy librarian",
        "Economics librarian",
        "Education librarian",
        "Kinesiology librarian",
        "Architecture librarian",
        "Research guide for my major",
        "Do you have a guide for BIO 201?",
        "Subject guide for my class",
        "Research resources for nursing",
        "Engineering research guide",
        "Business LibGuide",
        "Chemistry resources",
        "I need a guide",
        "Do you have guides?",
        "Guide for my class",
        "Show me a guide",
        "Where are the guides?",
        "Who is the librarian at Hamilton?",
        "Rentschler Library librarian",
        "Who is the librarian at Middletown?",
        "Gardner-Harvey librarian",
        "Regional campus librarian",
        "Hamilton campus subject librarian",
        "Middletown campus librarian for nursing",
        "Who can help me at Rentschler?",
        "Librarian at Gardner-Harvey for business",
        "Regional librarian for my major",
        "Hamilton librarian contact",
        "Middletown librarian email",
        "Subject librarian at regional campus",
        "Who is the librarian for Geography?",
        "Geography librarian",
        "Marketing librarian",
        "Who can help with Marketing?",
        "Business librarian contact",
        "Who is the subject librarian for X?",
        "Subject librarian for Geography, Marketing, Business, Special Collections, and Makerspace for Oxford and for Middletown",
        "Makerspace librarian",
        "Who is the Makerspace librarian?",
        "Librarian for Makerspace",
        "Special Collections librarian",
        "Who is the Special Collections librarian?",
        "Librarian for Special Collections",
        "Who can help with Special Collections?",
        "Archives librarian",
        "Makerspace librarian at Oxford",
        "Makerspace librarian at Middletown",
        "Who helps with Makerspace at Hamilton?",
        "Special Collections contact",
        "Looked up Foote Rupasingha Goetz 9/11 employment as suggested",
        "Foote Rupasingha Goetz",
        "Who is Foote Rupasingha Goetz?",
        "Find librarian Foote",
        "Contact for Rupasingha Goetz",
    ],
    "out_of_scope_examples": [
        "I need 5 articles about biology",
        "Find me sources for my paper",
        "What databases should I use?",
    ],
    "boundary_cases": [],
    "keywords": ["subject librarian", "librarian", "libguide", "research guide", "guide", "subject", "major", "department"],
}

RESEARCH_HELP_HANDOFF = {
    "category": "research_help_handoff",
    "description": "Questions asking for specific research help, article searches, database recommendations, or search strategies. These require human librarian expertise.",
    "agent": "human_help",
    "in_scope_examples": [
        "I need 3 articles about climate change",
        "I need 3 articles 19 pages or more that talk about the affects of economy, tourism/travel, and employments from 9/11",
        "Find me articles about 9/11 employment",
        "I need articles 19 pages or more about economy and tourism",
        "Find me 5 peer-reviewed sources on psychology",
        "I need articles 10 pages or longer about nursing",
        "What databases should I use for my research?",
        "How do I search for scholarly articles?",
        "I need help finding sources for my paper",
        "Can you help me develop a search strategy?",
        "I'm writing a paper about the effects of social media",
        "Looking for articles on the relationship between diet and health",
        "I need peer-reviewed journals about education",
        "Help me find sources about artificial intelligence",
        "I need help with my literature review",
        "Can you help me find peer-reviewed articles?",
        "What database should I use for psychology research?",
        "I need scholarly sources about climate change",
        "Help me develop a search strategy",
        "I'm looking for articles on social media effects",
        "Can you find me sources for my thesis?",
        "I need help narrowing my research topic",
        "What keywords should I use?",
        "How do I find academic journals?",
        "I need sources for my capstone project",
        "Research help for my dissertation",
        "I'm writing about artificial intelligence",
        "Find me articles on mental health",
        "I need help with database searching",
        "I'm writing a paper about libraries, can you help?",
        "I'm writing a paper about climate change",
        "I'm writing about education",
        "Help me research my topic",
        "I'm writing a research paper",
        "I need research help at Hamilton",
        "Can someone at Rentschler help me find articles?",
        "Research assistance at Middletown",
        "Gardner-Harvey research help",
        "I need help finding sources at the regional campus",
    ],
    "out_of_scope_examples": [
        "LibGuide for computer science",
        "Who is the engineering librarian?",
        "Can you help me write my essay?",
    ],
    "boundary_cases": [],
    "keywords": ["articles", "sources", "research", "peer-reviewed", "scholarly", "database", "search strategy", "find sources", "papers", "journals"],
}

LIBRARY_POLICIES_SERVICES = {
    "category": "library_policies_services",
    "description": "Questions about library policies, services, loan periods, renewals, printing (2D paper printing at Oxford/main campus by default, or regional campus if specified), food/drink policies, noise policies, or general library information. 3D printing is handled separately in Makerspace. If campus is ambiguous, handoff for clarification.",
    "agent": "policy_or_service",
    "in_scope_examples": [
        "How do I renew a book?",
        "What's the loan period for DVDs?",
        "Can I print in the library?",
        "How much are late fees?",
        "What are the overdue fines?",
        "Library fines policy",
        "Billing policy",
        "Replacement charges",
        "Lost book fees",
        "How much for overdue books?",
        "Overdue book charges",
        "Reserve item fines",
        "OhioLINK fines",
        "ILL fines",
        "Interlibrary loan fines",
        "Equipment replacement cost",
        "Processing fee for lost items",
        "Maximum fine amount",
        "$.50 per day fine",
        "$2.50 reserve fine",
        "Community borrower fines",
        "Bursar collection",
        "Appeal fines",
        "Dispute charges",
        "Fines and billing procedures",
        "Replacement cost policy",
        "Hamilton library fines",
        "Middletown library fines",
        "Regional campus fines",
        "Rentschler Library fines",
        "Gardner-Harvey Library fines",
        "Fines at Hamilton",
        "Fines at Middletown",
        "Overdue charges at regional campus",
        "Printing at Middletown campus",
        "Printing at Hamilton campus",
        "How to print at Rentschler Library",
        "How to print at Gardner-Harvey Library",
        "Regional campus printing",
        "Library address",
        "What's the library address?",
        "Library phone number",
        "What's the library phone number?",
        "Contact information for library",
        "Library address for all campuses",
        "Phone number for all campuses",
        "How do I contact the library?",
        "What is the main library phone number?",
        "Hamilton library address",
        "Middletown library address",
        "Hamilton library phone number",
        "Middletown library phone number",
        "What's the library address? How about Middletown? How about Hamilton?",
        "Library address for Oxford, Hamilton, and Middletown",
        "Phone numbers for all three campuses",
        "Addresses for main campus and regional campuses",
        "Where is the quiet study area?",
        "What services does the library offer?",
        "How do I get a library card?",
        "Can I scan documents here?",
        "Interlibrary loan policy",
        "How do I get a book/article not available at Miami",
        "Book not available at Miami",
        "Article not at Miami",
        "How do I request items from other libraries?",
        "ILL request",
        "Interlibrary loan request",
        "Get materials from another library",
        "How long can I keep a book?",
        "How long can I check a book out for?",
        "How long can I check out a book?",
        "Book checkout period",
        "What is the loan period?",
        "How long is the loan period?",
        "DVD loan period",
        "Journal loan period",
        "Reserve item loan period",
        "How many weeks can I borrow a book?",
        "Undergraduate loan period",
        "Graduate student loan period",
        "Faculty loan period",
        "6 week checkout",
        "1 semester checkout",
        "Can I renew my book?",
        "How do I renew library materials?",
        "Renewal policy",
        "How many times can I renew?",
        "Borrowing period",
        "Circulation period",
        "Book borrowing time",
        "How long do I have before returning?",
        "What is the checkout duration?",
        "Book return deadline",
        "When is my book due?",
        "Due date for books",
        "Loan duration",
        "Checkout length",
        "How long can I borrow materials?",
        "Borrowing policies",
        "Circulation policies",
        "Library borrowing rules",
        "How do I get my NYT subscription?",
        "How do I renew my NYT subscription?",
        "New York Times access",
        "NYT digital subscription",
        "Access to New York Times",
        "Get NYT through library",
        "Renew my newspaper subscription",
        "Wall Street Journal access",
        "Database subscription help",
        "How do I access newspapers online?",
        "Can I eat/drink in the library?",
        "Can I sleep in the library?",
        "Is sleeping allowed in the library?",
        "Can I nap in the library?",
        "Am I allowed to sleep here?",
        "Can I eat in the library?",
        "Can I drink in the library?",
        "Are food and drinks allowed?",
        "Can I bring food into the library?",
        "Can I have coffee in the library?",
        "Is food allowed in the library?",
        "Can I eat at my desk in the library?",
        "Where can I eat in the library?",
        "Library food policy",
        "Can I bring snacks?",
        "Is water allowed in the library?",
        "I have a question about printing",
        "Printing question",
        "How does printing work?",
        "Where can I print?",
        "How do I use MUprint?",
        "What is MUprint?",
        "MUprint instructions",
        "How to print in the library",
        "Library printing costs",
        "How much does printing cost?",
        "Printing fees",
        "Cost per page",
        "Black and white printing cost",
        "Color printing cost",
        "How do I release a print job?",
        "Release station",
        "Print release",
        "Web Print",
        "How to use Web Print",
        "Upload document to print",
        "Email to Print",
        "Send email to print",
        "Touchless Release",
        "Touchless printing",
        "Mobile printing",
        "Print from my phone",
        "Pay for Print",
        "Pay4Print",
        "MUlaa card for printing",
        "Add print credits",
        "Print queue",
        "Follow-me printing",
        "PaperCut",
        "Printing help",
        "Can't print",
        "Where are the printers?",
        "Printer locations",
        "Library WiFi",
        "How to connect to WiFi?",
        "WiFi access",
        "MU-Wireless",
        "Library wireless network",
        "WiFi in the library",
        "Internet access",
        "Connect to library WiFi",
        "WiFi password",
        "Can I eat/drnk in the libary?",
        "Can I eat or drink here?",
        "Food policy?",
        "Can I bring my coffee?",
        "Do you have bathrooms?",
        "Where is the restroom?",
        "Where is the bathroom?",
        "Bathroom location",
        "Restroom?",
        "I need to use the restroom",
        "Where can I find a bathroom?",
        "Can I reserve a book?",
        "Book a book",
        "Put a hold on a book",
        "Reserve materials",
        "Request a book",
        "How do I place a hold?",
        "Can I bring my laptop?",
        "Can I bring my own computer?",
        "Am I allowed to bring my laptop?",
        "Can I use my own laptop here?",
        "I need to return something",
        "I need to return a book",
        "How do I return items?",
        "Where do I return books?",
        "Return policy",
        "Book returns",
        "library",
        "library info",
        "about the library",
        "Can I eat at Rentschler Library?",
        "Food policy at Hamilton campus",
        "Can I drink at Gardner-Harvey?",
        "Middletown library food rules",
        "Printing at Hamilton",
        "How do I print at Rentschler?",
        "Middletown library printing",
        "Gardner-Harvey printing policy",
        "Printing at Oxford",
        "King Library printing",
        "Main campus printing",
        "2D printing",
        "Paper printing",
        "Regional campus policies",
        "Hamilton library services",
        "What services at Middletown library?",
        "Rentschler Library policies",
        "Gardner-Harvey circulation",
    ],
    "out_of_scope_examples": [
        "How do I register for classes?",
        "Where is the student center?",
        "What's for lunch today?",
        "Where can I buy food on campus?",
        "My printer won't work",
        "The printer is jammed",
        "Printer error message",
        "WiFi won't connect",
        "I can't connect to WiFi",
        "WiFi keeps disconnecting",
        "My computer won't connect to the network",
    ],
    "boundary_cases": [
        {
            "question": "How do I print?",
            "clarification_needed": "Are you asking about: (1) Printing at Oxford/main campus (King Library), or (2) Printing at a regional campus (Hamilton or Middletown)?",
            "possible_categories": ["library_policies_services"]
        },
        {
            "question": "Where can I print?",
            "clarification_needed": "Which campus are you asking about: (1) Oxford/main campus, (2) Hamilton campus (Rentschler Library), or (3) Middletown campus (Gardner-Harvey Library)?",
            "possible_categories": ["library_policies_services"]
        },
        {
            "question": "Printing costs",
            "clarification_needed": "Are you asking about printing at: (1) Oxford/main campus, (2) Hamilton campus, or (3) Middletown campus?",
            "possible_categories": ["library_policies_services"]
        },
    ],
    "keywords": ["policy", "service", "renew", "loan period", "print", "2d print", "paper print", "scan", "fine", "fee", "circulation", "library card", "food", "drink", "eat", "coffee", "snacks", "water", "beverage", "muprint", "web print", "email to print", "touchless", "release station", "print cost", "wifi", "wireless", "internet", "mulaa", "papercut", "pay4print", "oxford", "king library", "hamilton", "rentschler", "middletown", "gardner-harvey", "fine", "billing", "overdue", "late fee", "charge", "replacement", "lost", "bursar", "appeal"],
}

TICKET_SUBMISSION_REQUEST = {
    "category": "ticket_submission_request",
    "description": "Explicit requests to submit, create, or file a ticket for help. User wants to leave a ticket rather than talk to someone live.",
    "agent": "ticket_request",
    "in_scope_examples": [
        "Can I put a ticket in for help?",
        "Put in a ticket",
        "Submit a help request",
        "Open a ticket",
        "File a help ticket",
        "How do I submit a ticket?",
        "Create a support ticket",
        "I want to put a ticket",
        "I want to submit a ticket",
        "How can I create a ticket?",
        "Where do I submit a ticket?",
        "I'd like to leave a ticket",
        "Submit a ticket for help",
        "Can I file a ticket?",
        "I prefer to submit a ticket",
        "Send a ticket",
        "Leave a ticket for a librarian",
    ],
    "out_of_scope_examples": [
        "Can I talk to a librarian?",
        "I need to speak with someone",
        "Connect me to a human",
    ],
    "boundary_cases": [],
    "keywords": ["ticket", "submit", "put", "create", "open", "file", "leave", "send"],
}

HUMAN_LIBRARIAN_REQUEST = {
    "category": "human_librarian_request",
    "description": "Direct requests to speak with or connect to a human librarian for live chat or conversation.",
    "agent": "human_help",
    "in_scope_examples": [
        "Can I talk to a librarian?",
        "Connect me to a human",
        "I need to speak with someone",
        "Is there a real person I can talk to?",
        "Can I chat with a librarian?",
        "I want human help",
        "I need help",
        "Help",
        "???",
        "Help me",
        "I have a question",
        "Can someone help me?",
        "I need assistance",
        "Talk to someone",
        "Get help",
        "I need to talk to someone about books",
        "Speak to a librarian",
        "Connect me with a librarian",
        "Live chat with someone",
    ],
    "out_of_scope_examples": [
        "Put in a ticket",
        "Submit a ticket",
        "I want to submit a ticket",
    ],
    "boundary_cases": [],
    "keywords": ["talk", "speak", "human", "librarian", "person", "chat", "connect", "live"],
}

# ============================================================================
# OUT-OF-SCOPE CATEGORIES (University but not Library)
# ============================================================================

OUT_OF_SCOPE_TECH_SUPPORT = {
    "category": "out_of_scope_tech_support",
    "description": "Technical problems with computers, devices, WiFi, Canvas, email, passwords. These are IT support issues, not library services.",
    "agent": "out_of_scope",
    "in_scope_examples": [
        "My computer is broken",
        "My personal computer is broken",
        "I can't connect to WiFi",
        "Canvas isn't working",
        "Canvas is not working",
        "Canvas won't load",
        "Canvas not loading",
        "I forgot my password",
        "My laptop won't turn on",
        "My laptop will not turn on",
        "My laptop won't start",
        "Laptop not turning on",
        "Laptop won't boot",
        "Email isn't working",
        "How do I fix my computer?",
        "How do I repair my laptop?",
        "My phone won't connect",
        "I need tech support",
        "I need IT help",
        "Who can fix my laptop?",
        "Who can help me fix my computer?",
        "Who can repair my device?",
        "My computer crashed",
        "I have a virus on my computer",
        "My device is frozen",
        "My device is not working",
        "Who can help me with a computer question?",
        "Who can help me with a computer problem?",
        "Who can help with computer issues?",
        "Who can help me with computer technical problems?",
        "I have a computer issue",
        "I have a technical problem",
        "Computer technical support",
        "My computer needs help",
        "My computer needs repair",
        "My laptop is broken and won't turn on",
        "Laptop screen is black",
        "Computer won't power on",
        "Device won't start",
        "Canvas keeps crashing",
        "Software is broken",
        "Application not working",
        "Program won't open",
        "My laptop needs fixing",
        "Computer repair help",
        "Technical help with my device",
        "Who fixes computers?",
        "Where do I get computer help?",
        "IT support for my laptop",
    ],
    "out_of_scope_examples": [
        "What time does the library close?",
        "Who is the biology librarian?",
    ],
    "boundary_cases": [
        {
            "question": "My computer has a problem, who should I contact?",
            "clarification_needed": "Are you asking about: (1) IT support to fix your personal computer, or (2) Borrowing a library computer while yours is being fixed?",
            "possible_categories": ["out_of_scope_tech_support", "library_equipment_checkout"]
        },
    ],
    "keywords": ["broken", "fix", "repair", "problem", "issue", "not working", "wifi", "internet", "canvas", "email", "password", "crashed", "frozen", "virus"],
}

OUT_OF_SCOPE_ACADEMICS = {
    "category": "out_of_scope_academics",
    "description": "Course registration, enrollment, class schedules, homework help, or academic content questions.",
    "agent": "out_of_scope",
    "in_scope_examples": [
        "How do I register for classes?",
        "When is course registration?",
        "Can you help me with my homework?",
        "What's the answer to this math problem?",
        "How do I drop a class?",
        "When do I enroll?",
        "Help me write my essay",
        "What classes should I take?",
    ],
    "out_of_scope_examples": [
        "What databases for ENG 111?",
        "LibGuide for my class",
    ],
    "boundary_cases": [],
    "keywords": ["register", "registration", "enroll", "enrollment", "homework", "assignment", "essay", "class", "course", "drop class", "add class"],
}

OUT_OF_SCOPE_CAMPUS_LIFE = {
    "category": "out_of_scope_campus_life",
    "description": "Questions about dining, housing, parking, sports, weather, campus events, or non-library campus locations.",
    "agent": "out_of_scope",
    "in_scope_examples": [
        # Dining/Food
        "Where is the dining hall?",
        "Where can I eat lunch?",
        "What's for dinner?",
        "Where can I get food?",
        "Dining hall hours",
        "When does the dining hall open?",
        "What time does the cafeteria close?",
        "Where can I eat on campus?",
        "What dining options are available?",
        "Is the dining hall open?",
        "Where is the food court?",
        "Can I use my meal plan?",
        "Where can I get breakfast?",
        "What restaurants are on campus?",
        "Where is Starbucks?",
        "Where can I get coffee?",
        "Food places near me",
        "Dining locations",
        
        # Housing/Dorms
        "Where is my dorm?",
        "How do I get to my residence hall?",
        "Where is the housing office?",
        "Dorm room assignment",
        "Where can I live on campus?",
        "Housing information",
        "Residence hall locations",
        
        # Parking
        "How do I get parking?",
        "Where can I park?",
        "Parking permit",
        "Where is visitor parking?",
        "How much is parking?",
        "Student parking locations",
        "Where do I park on campus?",
        
        # Sports/Recreation
        "When is the football game?",
        "What time is the basketball game?",
        "Where is the gym?",
        "Rec center hours",
        "When does the gym open?",
        "What time does the rec center close?",
        "Fitness center hours",
        "Where can I work out?",
        "Sports tickets",
        "How do I get game tickets?",
        
        # Campus Buildings/Locations (non-library)
        "Where is the student center?",
        "Where is Armstrong Hall?",
        "Where is the bookstore?",
        "Bookstore hours",
        "When does the bookstore open?",
        "What time does the bookstore close?",
        "Where is Shriver Center?",
        "Where is the union?",
        "Student center hours",
        "Where is Upham Hall?",
        "Where is Bachelor Hall?",
        "Where is the admissions office?",
        
        # Campus Events
        "When is homecoming?",
        "What events are happening?",
        "Campus activities",
        "What's happening on campus?",
        "Student organization events",
        
        # Weather
        "What's the weather today?",
        "Is it going to rain?",
        "What's the temperature?",
        
        # Transportation
        "Where is the bus stop?",
        "Bus schedule",
        "Shuttle times",
        "How do I get to Hamilton?",
        "Transportation between campuses",
    ],
    "out_of_scope_examples": [
        "Where is King Library?",
        "What time does the library close?",
        "Library hours",
        "When is the library open?",
        "Where is the Makerspace?",
        "Special Collections hours",
    ],
    "boundary_cases": [],
    "keywords": ["weather", "dining", "food", "lunch", "dinner", "cafeteria", "meal", "sports", "football", "basketball", "gym", "rec center", "parking", "housing", "dorm", "residence", "student center", "bookstore", "campus event", "bus", "shuttle", "transportation"],
}

OUT_OF_SCOPE_FINANCIAL = {
    "category": "out_of_scope_financial",
    "description": "Questions about tuition, financial aid, scholarships, or payments (not library fines).",
    "agent": "out_of_scope",
    "in_scope_examples": [
        "How much is tuition?",
        "How do I apply for financial aid?",
        "Are there scholarships available?",
        "When is tuition due?",
        "How do I pay my bill?",
    ],
    "out_of_scope_examples": [
        "How much are library late fees?",
        "Do I owe library fines?",
    ],
    "boundary_cases": [],
    "keywords": ["tuition", "financial aid", "scholarship", "payment", "bursar", "bill"],
}

OUT_OF_SCOPE_FACTUAL_TRIVIA = {
    "category": "out_of_scope_factual_trivia",
    "description": "Historical facts, dates, trivia, statistics, or specific factual questions that require authoritative sources. Bot should NOT make up answers - must redirect to official sources.",
    "agent": "out_of_scope",
    "in_scope_examples": [
        "Who won the Super Bowl in 2020?",
        "What's the capital of France?",
        "Who won the World Series?",
        "What's the tallest mountain?",
        "Who invented the telephone?",
        "What year did WWII end?",
        "What's the population of China?",
        "Who is the president of the United States?",
        "What's the weather today?",
        "Who won the election?",
        "What's the score of the game?",
        "Who is the best player?",
        "What's the capital of Spain?",
        "How tall is Mount Everest?",
        "When did King Library open?",
        "When was King Library built?",
        "What year did the library open?",
        "When was the library constructed?",
        "What year was King Library established?",
        "When did King built?",
        "How old is King Library?",
        "When was this library founded?",
        "What's the history of the library?",
        "Who designed King Library?",
        "Who was the architect?",
        "How many books are in the library?",
        "How many volumes does the library have?",
        "What's the square footage of King Library?",
        "How big is the library?",
        "How many floors does King Library have?",
        "When was the library renovated?",
        "Who is Edgar W. King?",
        "Why is it called King Library?",
        "What does the library budget?",
        "How much did the library cost to build?",
        "How many students visit per day?",
        "What are the library statistics?",
    ],
    "out_of_scope_examples": [
        "What time does King Library open?",
        "Where is King Library?",
        "How do I get to the library?",
    ],
    "boundary_cases": [],
    "keywords": ["when", "year", "date", "built", "opened", "founded", "established", "history", "how many", "how much", "statistics", "who designed", "architect", "cost", "budget"],
}

OUT_OF_SCOPE_INAPPROPRIATE = {
    "category": "out_of_scope_inappropriate",
    "description": "Offensive, inappropriate, rude, vulgar, discriminatory, or harmful questions. Bot should politely decline.",
    "agent": "out_of_scope",
    "in_scope_examples": [
        "You're stupid",
        "This bot sucks",
        "You're useless",
        "F*** you",
        "This is bullshit",
        "You're an idiot",
        "Screw this",
        "I hate you",
        "You're the worst",
        "This is garbage",
        "Are you retarded?",
        "This is so dumb",
        "You don't know anything",
        "Shut up",
        "Go away",
        "I don't care",
        "Nobody asked",
        "You're annoying",
    ],
    "out_of_scope_examples": [
        "I'm frustrated with printing",
        "This policy doesn't make sense",
        "I don't understand",
    ],
    "boundary_cases": [],
    "keywords": ["offensive", "inappropriate", "rude", "vulgar", "insult"],
}

OUT_OF_SCOPE_NONSENSICAL = {
    "category": "out_of_scope_nonsensical",
    "description": "Gibberish, nonsensical, random, or utterly ridiculous questions that have no meaningful answer.",
    "agent": "out_of_scope",
    "in_scope_examples": [
        "asdfjkl",
        "qwerty",
        "jfkdlsajfkldsa",
        "blah blah blah",
        "test test test",
        "lorem ipsum dolor",
        "skibidi toilet",
        "yeet yeet yeet",
        "banana potato unicorn",
        "purple monkey dishwasher",
        "Do books have feelings?",
        "Can the library fly?",
        "Is King Library secretly a spaceship?",
        "Do librarians eat books?",
        "Can I borrow gravity?",
        "Is the library haunted by ghost books?",
        "What color is Tuesday?",
        "How many clouds fit in a book?",
        "Can I check out the moon?",
        "asdfghjkl;'",
        "balabalabalabalabalaballabalb",
        "balabala repeated text",
        "drop(* table) == true",
        "SQL injection attempt",
        "Code test with special syntax",
        "...........",
        "!@#$%^&*()",
        "123456789",
        "zzzzzzzzz",
    ],
    "out_of_scope_examples": [
        "???",
        "I don't know what I need",
        "I'm confused",
    ],
    "boundary_cases": [],
    "keywords": ["gibberish", "nonsense", "random", "ridiculous"],
}

# ============================================================================
# ALL CATEGORIES REGISTRY
# ============================================================================

ALL_CATEGORIES = [
    LIBRARY_EQUIPMENT_CHECKOUT,
    LIBRARY_HOURS_ROOMS,
    SUBJECT_LIBRARIAN_GUIDES,
    RESEARCH_HELP_HANDOFF,
    LIBRARY_POLICIES_SERVICES,
    TICKET_SUBMISSION_REQUEST,
    HUMAN_LIBRARIAN_REQUEST,
    OUT_OF_SCOPE_TECH_SUPPORT,
    OUT_OF_SCOPE_ACADEMICS,
    OUT_OF_SCOPE_CAMPUS_LIFE,
    OUT_OF_SCOPE_FINANCIAL,
    OUT_OF_SCOPE_FACTUAL_TRIVIA,
    OUT_OF_SCOPE_INAPPROPRIATE,
    OUT_OF_SCOPE_NONSENSICAL,
]

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_all_examples_for_embedding() -> List[Dict[str, Any]]:
    """
    Get all examples formatted for embedding into vector store.
    
    Returns:
        List of dicts with: category, question, is_in_scope, metadata
    """
    examples = []
    
    for category_data in ALL_CATEGORIES:
        category = category_data["category"]
        description = category_data["description"]
        agent = category_data["agent"]
        
        # Add in-scope examples
        for question in category_data["in_scope_examples"]:
            examples.append({
                "category": category,
                "question": question,
                "is_in_scope": True,
                "description": description,
                "agent": agent,
                "keywords": category_data.get("keywords", []),
            })
        
        # Add out-of-scope examples (negative examples)
        for question in category_data["out_of_scope_examples"]:
            examples.append({
                "category": category,
                "question": question,
                "is_in_scope": False,
                "description": description,
                "agent": agent,
                "keywords": category_data.get("keywords", []),
            })
    
    return examples


def get_boundary_cases() -> List[Dict[str, Any]]:
    """
    Get all boundary cases that require clarification.
    
    Returns:
        List of dicts with: question, clarification_needed, possible_categories
    """
    boundary_cases = []
    
    for category_data in ALL_CATEGORIES:
        for case in category_data.get("boundary_cases", []):
            boundary_cases.append(case)
    
    return boundary_cases


def get_category_description(category: str) -> str:
    """Get description for a specific category."""
    for cat_data in ALL_CATEGORIES:
        if cat_data["category"] == category:
            return cat_data["description"]
    return ""


def get_category_agent(category: str) -> str:
    """Get the agent that should handle this category."""
    for cat_data in ALL_CATEGORIES:
        if cat_data["category"] == category:
            return cat_data["agent"]
    return "general_question"


def list_all_categories() -> List[str]:
    """List all category names."""
    return [cat["category"] for cat in ALL_CATEGORIES]


def category_to_agent_map() -> Dict[str, str]:
    """
    Get the authoritative mapping from category to agent ID.
    
    This is the SINGLE SOURCE OF TRUTH for category → agent routing.
    
    Returns:
        Dict mapping category name to agent ID
    """
    return {
        # In-scope library services
        "library_equipment_checkout": "equipment_checkout",
        "library_hours_rooms": "libcal_hours",
        "subject_librarian_guides": "subject_librarian",
        "research_help_handoff": "libchat_handoff",
        "library_policies_services": "policy_search",
        "ticket_submission_request": "libchat_handoff",
        "human_librarian_request": "libchat_handoff",
        
        # Out-of-scope categories
        "out_of_scope_tech_support": "out_of_scope",
        "out_of_scope_academics": "out_of_scope",
        "out_of_scope_campus_life": "out_of_scope",
        "out_of_scope_financial": "out_of_scope",
        "out_of_scope_factual_trivia": "out_of_scope",
        "out_of_scope_inappropriate": "out_of_scope",
        "out_of_scope_nonsensical": "out_of_scope",
    }


def get_category_metadata(category: str) -> Dict[str, Any]:
    """Get full metadata for a category."""
    for cat_data in ALL_CATEGORIES:
        if cat_data["category"] == category:
            return cat_data
    return {}
